/**
 * @file    motor_control.c
 * @brief   Six-step BLDC motor control implementation for STM32G431
 *
 * Hardware assumed:
 *   - TIM1 configured as centre-aligned PWM with complementary outputs
 *     (CH1/CH1N, CH2/CH2N, CH3/CH3N) and dead-time insertion.
 *   - HAL_TIM_PWM_Start / HAL_TIMEx_PWMN_Start used to enable individual
 *     channels; HAL_TIM_PWM_Stop / HAL_TIMEx_PWMN_Stop to float them.
 *   - htim1, hadc1 extern handles assumed generated by STM32CubeMX.
 *
 * Adapt the HAL calls (TIM_CCR write, channel enable/disable) to your
 * actual peripheral handle names and BSP as needed.
 */

#include "motor_control.h"
#include "bemf.h"
#include <string.h>

/* ─── Extern peripheral handles (generated by STM32CubeMX) ────────────────── */
/*
 * Uncomment when integrating with a real HAL project:
 *
 * extern TIM_HandleTypeDef htim1;
 */

/* ─── Six-step commutation table ──────────────────────────────────────────── */
/*
 * Indexed by step number (0–5).  Each entry specifies the state of phases
 * A, B, and C:
 *
 *   Step │ Phase A │ Phase B │ Phase C │ BEMF on
 *   ─────┼─────────┼─────────┼─────────┼────────
 *     0  │  HIGH   │   LOW   │ FLOAT   │   C
 *     1  │  HIGH   │  FLOAT  │   LOW   │   B
 *     2  │  FLOAT  │  HIGH   │   LOW   │   A
 *     3  │   LOW   │  HIGH   │  FLOAT  │   C
 *     4  │   LOW   │  FLOAT  │  HIGH   │   B
 *     5  │  FLOAT  │   LOW   │  HIGH   │   A
 */
static const CommStep_t s_commTable[MOTOR_STEP_COUNT] = {
    /* Step 0 */ { PHASE_HIGH,     PHASE_LOW,      PHASE_FLOATING },
    /* Step 1 */ { PHASE_HIGH,     PHASE_FLOATING, PHASE_LOW      },
    /* Step 2 */ { PHASE_FLOATING, PHASE_HIGH,     PHASE_LOW      },
    /* Step 3 */ { PHASE_LOW,      PHASE_HIGH,     PHASE_FLOATING },
    /* Step 4 */ { PHASE_LOW,      PHASE_FLOATING, PHASE_HIGH     },
    /* Step 5 */ { PHASE_FLOATING, PHASE_LOW,      PHASE_HIGH     },
};

/* ─── Internal helpers ─────────────────────────────────────────────────────── */

/**
 * @brief Clamp a value to the allowed duty cycle range.
 */
static uint16_t ClampDuty(uint16_t duty)
{
    if (duty < PWM_DUTY_MIN_PERMILLE) { return PWM_DUTY_MIN_PERMILLE; }
    if (duty > PWM_DUTY_MAX_PERMILLE) { return PWM_DUTY_MAX_PERMILLE; }
    return duty;
}

/**
 * @brief Convert per-mille duty cycle to TIM1 CCR value.
 */
static uint32_t DutyToCcr(uint16_t dutyPermille)
{
    return ((uint32_t)dutyPermille * (PWM_ARR_VALUE + 1U)) / 1000U;
}

/**
 * @brief Apply phase output state to TIM1 complementary channels.
 *
 * Replace HAL stub calls with real HAL_TIM_PWM_Start / _Stop when
 * integrating with a CubeMX-generated project.
 *
 * @param phase  Phase index: 0 = A, 1 = B, 2 = C.
 * @param state  Desired output state for that phase.
 * @param ccr    PWM compare value (used when state == PHASE_HIGH).
 */
static void ApplyPhase(uint8_t phase, PhaseState_t state, uint32_t ccr)
{
    /*
     * TIM1 channel numbers (1-indexed as per HAL):
     *   Phase A → CH1 / CH1N
     *   Phase B → CH2 / CH2N
     *   Phase C → CH3 / CH3N
     *
     * Pseudo-code (replace with your HAL calls):
     *
     * uint32_t ch    = TIM_CHANNEL_1 << (phase * 4);   // CH1, CH2, or CH3
     * uint32_t chN   = TIM_CHANNEL_1N << (phase * 4);
     *
     * switch (state) {
     * case PHASE_HIGH:
     *     __HAL_TIM_SET_COMPARE(&htim1, ch, ccr);
     *     HAL_TIM_PWM_Start(&htim1, ch);
     *     HAL_TIMEx_PWMN_Start(&htim1, ch);   // enable complementary
     *     break;
     * case PHASE_LOW:
     *     __HAL_TIM_SET_COMPARE(&htim1, ch, 0U);
     *     HAL_TIM_PWM_Start(&htim1, ch);
     *     HAL_TIMEx_PWMN_Start(&htim1, ch);
     *     break;
     * case PHASE_FLOATING:
     *     HAL_TIM_PWM_Stop(&htim1, ch);
     *     HAL_TIMEx_PWMN_Stop(&htim1, ch);
     *     break;
     * }
     */
    (void)phase;
    (void)state;
    (void)ccr;
}

/**
 * @brief Disable all three phase outputs (MOE = 0 or all channels stopped).
 */
static void DisableAllPhases(void)
{
    /*
     * HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_1);
     * HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_2);
     * HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_3);
     * HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_1);
     * HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_2);
     * HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_3);
     */
}

/**
 * @brief Estimate mechanical speed from the electrical commutation period.
 *
 * @param commPeriodUs  Electrical commutation period in µs
 *                      (time between two consecutive zero-crossings).
 * @return Mechanical speed in RPM, or 0 on invalid input.
 */
static uint32_t CalcSpeedRpm(uint32_t commPeriodUs)
{
    if (commPeriodUs == 0U) { return 0U; }

    /*
     * One electrical revolution = MOTOR_STEP_COUNT commutation steps.
     * Period per revolution = commPeriodUs * MOTOR_STEP_COUNT  (µs).
     * Mechanical RPM = 60 * 1e6 / (period_us * POLE_PAIRS).
     */
    uint32_t elecPeriodUs = commPeriodUs * MOTOR_STEP_COUNT;
    uint32_t mechPeriodUs = elecPeriodUs * MOTOR_POLE_PAIRS;

    if (mechPeriodUs == 0U) { return 0U; }

    return (60U * 1000000U) / mechPeriodUs;
}

/* ─── Open-loop startup state ─────────────────────────────────────────────── */

static uint32_t s_startupPeriodUs  = STARTUP_COMM_PERIOD_INIT_US;
static uint32_t s_startupTickCount = 0U;

/* ─── Public API implementation ───────────────────────────────────────────── */

void Motor_Init(MotorHandle_t *hMotor)
{
    memset(hMotor, 0, sizeof(*hMotor));
    hMotor->state         = MOTOR_STATE_IDLE;
    hMotor->fault         = MOTOR_FAULT_NONE;
    hMotor->step          = 0U;
    hMotor->dutyPermille  = 0U;
    hMotor->targetDuty    = 0U;
    hMotor->commPeriodUs  = 0U;
    hMotor->speedRpm      = 0U;
    hMotor->bemfValidCount = 0U;

    DisableAllPhases();
}

void Motor_Start(MotorHandle_t *hMotor, uint16_t dutyPermille)
{
    if (hMotor->state == MOTOR_STATE_FAULT) { return; }

    hMotor->targetDuty      = ClampDuty(dutyPermille);
    hMotor->dutyPermille    = STARTUP_DUTY_PERMILLE;
    hMotor->step            = 0U;
    hMotor->bemfValidCount  = 0U;
    s_startupPeriodUs       = STARTUP_COMM_PERIOD_INIT_US;
    s_startupTickCount      = 0U;
    hMotor->state           = MOTOR_STATE_STARTUP;

    Motor_Commutate(hMotor);
}

void Motor_Stop(MotorHandle_t *hMotor)
{
    DisableAllPhases();
    hMotor->state        = MOTOR_STATE_IDLE;
    hMotor->dutyPermille = 0U;
    hMotor->speedRpm     = 0U;
}

void Motor_SetDuty(MotorHandle_t *hMotor, uint16_t dutyPermille)
{
    hMotor->targetDuty = ClampDuty(dutyPermille);
}

void Motor_Commutate(MotorHandle_t *hMotor)
{
    if ((hMotor->state != MOTOR_STATE_STARTUP) &&
        (hMotor->state != MOTOR_STATE_RUNNING))
    {
        return;
    }

    const CommStep_t *step = &s_commTable[hMotor->step];
    uint32_t ccr = DutyToCcr(hMotor->dutyPermille);

    ApplyPhase(0U, step->phA, ccr);
    ApplyPhase(1U, step->phB, ccr);
    ApplyPhase(2U, step->phC, ccr);

    /* Advance step */
    hMotor->step = (hMotor->step + 1U) % MOTOR_STEP_COUNT;
}

void Motor_Task1ms(MotorHandle_t *hMotor)
{
    switch (hMotor->state)
    {
    case MOTOR_STATE_STARTUP:
    {
        s_startupTickCount++;

        /* Open-loop commutation timing */
        uint32_t periodMs = s_startupPeriodUs / 1000U;
        if (periodMs == 0U) { periodMs = 1U; }

        if (s_startupTickCount >= periodMs)
        {
            s_startupTickCount = 0U;
            Motor_Commutate(hMotor);

            /* Ramp down commutation period */
            if (s_startupPeriodUs > STARTUP_COMM_PERIOD_MIN_US + 100U)
            {
                s_startupPeriodUs -= 100U;
            }
        }

        /* Transition to closed-loop if enough BEMF crossings confirmed */
        if (hMotor->bemfValidCount >= STARTUP_BEMF_VALID_COUNT)
        {
            hMotor->dutyPermille = hMotor->targetDuty;
            hMotor->state        = MOTOR_STATE_RUNNING;
        }

        /* Stall detection: still in startup after a long period */
        if (s_startupPeriodUs <= STARTUP_COMM_PERIOD_MIN_US &&
            hMotor->bemfValidCount == 0U)
        {
            hMotor->fault = MOTOR_FAULT_STALL;
            hMotor->state = MOTOR_STATE_FAULT;
            DisableAllPhases();
        }
        break;
    }

    case MOTOR_STATE_RUNNING:
    {
        /* Gradual duty ramp toward target */
        if (hMotor->dutyPermille < hMotor->targetDuty)
        {
            hMotor->dutyPermille++;
        }
        else if (hMotor->dutyPermille > hMotor->targetDuty)
        {
            hMotor->dutyPermille--;
        }

        /* Update speed estimate */
        if (hMotor->commPeriodUs > 0U)
        {
            hMotor->speedRpm = CalcSpeedRpm(hMotor->commPeriodUs);
        }
        break;
    }

    case MOTOR_STATE_IDLE:
    case MOTOR_STATE_FAULT:
    default:
        break;
    }
}

void Motor_ClearFault(MotorHandle_t *hMotor)
{
    hMotor->fault = MOTOR_FAULT_NONE;
    hMotor->state = MOTOR_STATE_IDLE;
    DisableAllPhases();
}

uint32_t Motor_GetSpeedRpm(const MotorHandle_t *hMotor)
{
    return hMotor->speedRpm;
}

MotorState_t Motor_GetState(const MotorHandle_t *hMotor)
{
    return hMotor->state;
}
